### ISSUE TITLE
fail to install spatstat.sphere

### ISSUE THREAD

**Issue by natemiller** [spatstat/spatstat.sphere#1]
I am trying to install the spatstat.sphere plugin to spatstat/s2 using devtools and I received the error ``` namespace ‘s2’ 0.1-1 is being loaded, but >= 0.2.1 is required```. However, from CRAN the latest version of s2 that I am able to load is 0.1-1. 

I am using R v 3.4.1 and have tried to ensure I have all build tools available, though with the newest version of R that has been challenging. 

Any advice on how to access the more recent version of s2 so I can use the spatstat.sphere? Will this version of s2 be added to CRAN or can the functions spatstat.sphere be included in the s2 package?

**Comment by rubak** [comment]
Which operating system are you on and how did you install `spatstat.sphere`? If you use `install_github` from either `devtools` or the `remotes` package it should also install `s2` from GitHub, which is version `0.2-1`. If the problem is that you don't have all the necessary build tools you may be able to install binaries from appveyor if you are on windows. If you are on Mac I can try to make a pre-release on GitHub with binaries you can install.

**Comment by natemiller** [comment]
I on MacOS 10.12.6 (Sierra) and trying to install using install_github. I have Xcode command line tools installed and when I run devtools::install_github('spatstat/spatstat.sphere') I get an installation failed: Could not find build tools necessary to build spatstat. I feel like I should have all the necessary build tools, but find I cannot install `spatstat` alone using install_github('spatstat/spatstat') either.

**Comment by rubak** [comment]
Did you log out and in again after installing the extensions to XCode? Maybe some environment variables need to be set for R to find you compiler... 
Could you try to install `Rcpp` and run the example in `?sourceCpp` to see if you can compile a simple function?

     sourceCpp(code='
       #include <Rcpp.h>
     
       // [[Rcpp::export]]
       int fibonacci(const int x) {
         if (x == 0) return(0);
         if (x == 1) return(1);
         return (fibonacci(x - 1)) + fibonacci(x - 2);
       }'
     )

I will see if I can make a binary release for OSX here on GitHub sometime tomorrow (European time).

**Comment by natemiller** [comment]
Thank you for your help troubleshooting. I wasn't able to build that simple function with the error `sh: make: command not found` and `sh: rm : command not found`. Both of these binaries are available on my computer in `/bin`and I've checked that `/bin` is in my $PATH so I'm not certain why they cannot be found. Given these errors is doesn't seem to be an issue with the `spatstat` however.

**Comment by rubak** [comment]
OK. I have made a binary release of `s2` so please try to download and install that:

https://github.com/spatstat/s2/releases/download/v0.2-1/s2_0.2-1.tgz

**Comment by natemiller** [comment]
Yes. Thank you, that has worked. Thank you for your assistance with this, I
greatly appreciate your time.

**Comment by baddstats** [comment]
I believe this issue is now closed.
