### ISSUE TITLE
s2dist error "Don't know how to extract longitude and latitude from these data" 

### ISSUE THREAD

**Issue by upascal** [spatstat/spatstat.sphere#4]
```
> s2dist(lng,lat)
Error in globe::ensurelonlat(x) : 
  Don't know how to extract longitude and latitude from these data

> lat[20]
[1] 48.14462
> lng[20]
[1] 11.57023
> s2dist(lat[20], lng[20])
Error in globe::ensurelonlat(x) : 
  Don't know how to extract longitude and latitude from these data
```

I'm trying to compute haversine distances for my lat,lng points but when I try to use s2dist I get this error. It doesn't seem to matter whether I input a list, vector or single value. I am always getting the same error. I have not issues making an s2pp object with my data, and it plots fine with iplot.

**Comment by rubak** [comment]
Do you want all pairwise distances between points in a `s2pp` object called e.g. `X`? Then you can use `spatstat.sphere:::pairdist.s2pp(X)`. It is a mistake that you need the triple colon, and I will fix it soon. You can also use `s2dist()` to calculate distances, but you have to supply a `data.frame` with lon,lat as `x` and another `data.frame` with lon,lat as `y`, and then you get the distances between the points listed in `x` and `y`.

**Comment by upascal** [comment]
Sorry this was a mistake on my part!  I figured it out. Thanks
